#ifndef CONFIGURATION_H
#define CONFIGURATION_H
#define FILE_GRANULARITY 4
#define MINIMAL_TUPLE_SIZE 256
#define SINGLE_TUPLE_VALUE_SIZE 8
#define OFFSET_VALUE_SIZE 8
#define NULL_VALUE 0
#define BIG_ENDIAN_SIGNATURE 0xFFFE
#define RESERVED_CELLS 16

#endif
